
package sample.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShopService", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/passexam")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShopService {


    /**
     * 
     * @return
     *     returns sample.client.ShopCatalog
     */
    @WebMethod(operationName = "GetShopCatalog")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetShopCatalog", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/passexam", className = "sample.client.GetShopCatalog")
    @ResponseWrapper(localName = "GetShopCatalogResponse", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/passexam", className = "sample.client.GetShopCatalogResponse")
    @Action(input = "http://asu.dgtu.donetsk.ua/ex/passexam/ShopService/GetShopCatalogRequest", output = "http://asu.dgtu.donetsk.ua/ex/passexam/ShopService/GetShopCatalogResponse")
    public ShopCatalog getShopCatalog();

}
