
package sample.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShowCatalog", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/passexam", wsdlLocation = "http://localhost:8081/ShopSvcWeb/ShowCatalog?wsdl")
public class ShowCatalog
    extends Service
{

    private final static URL SHOWCATALOG_WSDL_LOCATION;
    private final static WebServiceException SHOWCATALOG_EXCEPTION;
    private final static QName SHOWCATALOG_QNAME = new QName("http://asu.dgtu.donetsk.ua/ex/passexam", "ShowCatalog");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ShopSvcWeb/ShowCatalog?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHOWCATALOG_WSDL_LOCATION = url;
        SHOWCATALOG_EXCEPTION = e;
    }

    public ShowCatalog() {
        super(__getWsdlLocation(), SHOWCATALOG_QNAME);
    }

    public ShowCatalog(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHOWCATALOG_QNAME, features);
    }

    public ShowCatalog(URL wsdlLocation) {
        super(wsdlLocation, SHOWCATALOG_QNAME);
    }

    public ShowCatalog(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHOWCATALOG_QNAME, features);
    }

    public ShowCatalog(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShowCatalog(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShopService
     */
    @WebEndpoint(name = "ShowCatalogPort")
    public ShopService getShowCatalogPort() {
        return super.getPort(new QName("http://asu.dgtu.donetsk.ua/ex/passexam", "ShowCatalogPort"), ShopService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShopService
     */
    @WebEndpoint(name = "ShowCatalogPort")
    public ShopService getShowCatalogPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://asu.dgtu.donetsk.ua/ex/passexam", "ShowCatalogPort"), ShopService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHOWCATALOG_EXCEPTION!= null) {
            throw SHOWCATALOG_EXCEPTION;
        }
        return SHOWCATALOG_WSDL_LOCATION;
    }

}
