
package async.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReservationGoods", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/students", wsdlLocation = "http://localhost:8082/ReservationGoods?wsdl")
public class ReservationGoods
    extends Service
{

    private final static URL RESERVATIONGOODS_WSDL_LOCATION;
    private final static WebServiceException RESERVATIONGOODS_EXCEPTION;
    private final static QName RESERVATIONGOODS_QNAME = new QName("http://asu.dgtu.donetsk.ua/ex/students", "ReservationGoods");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/ReservationGoods?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVATIONGOODS_WSDL_LOCATION = url;
        RESERVATIONGOODS_EXCEPTION = e;
    }

    public ReservationGoods() {
        super(__getWsdlLocation(), RESERVATIONGOODS_QNAME);
    }

    public ReservationGoods(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATIONGOODS_QNAME, features);
    }

    public ReservationGoods(URL wsdlLocation) {
        super(wsdlLocation, RESERVATIONGOODS_QNAME);
    }

    public ReservationGoods(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATIONGOODS_QNAME, features);
    }

    public ReservationGoods(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationGoods(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReservationGoodsService
     */
    @WebEndpoint(name = "ReservationGoodsPort")
    public ReservationGoodsService getReservationGoodsPort() {
        return super.getPort(new QName("http://asu.dgtu.donetsk.ua/ex/students", "ReservationGoodsPort"), ReservationGoodsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservationGoodsService
     */
    @WebEndpoint(name = "ReservationGoodsPort")
    public ReservationGoodsService getReservationGoodsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://asu.dgtu.donetsk.ua/ex/students", "ReservationGoodsPort"), ReservationGoodsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATIONGOODS_EXCEPTION!= null) {
            throw RESERVATIONGOODS_EXCEPTION;
        }
        return RESERVATIONGOODS_WSDL_LOCATION;
    }

}
