
package sample.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PassExam", targetNamespace = "http://asu.dgtu.donetsk.ua/ex/passexam", wsdlLocation = "http://127.0.0.1:8084/ExamSvcWeb/exampass?wsdl")
public class PassExam
    extends Service
{

    private final static URL PASSEXAM_WSDL_LOCATION;
    private final static WebServiceException PASSEXAM_EXCEPTION;
    private final static QName PASSEXAM_QNAME = new QName("http://asu.dgtu.donetsk.ua/ex/passexam", "PassExam");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8084/ExamSvcWeb/exampass?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PASSEXAM_WSDL_LOCATION = url;
        PASSEXAM_EXCEPTION = e;
    }

    public PassExam() {
        super(__getWsdlLocation(), PASSEXAM_QNAME);
    }

    public PassExam(WebServiceFeature... features) {
        super(__getWsdlLocation(), PASSEXAM_QNAME, features);
    }

    public PassExam(URL wsdlLocation) {
        super(wsdlLocation, PASSEXAM_QNAME);
    }

    public PassExam(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PASSEXAM_QNAME, features);
    }

    public PassExam(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PassExam(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExamService
     */
    @WebEndpoint(name = "PassExamPort")
    public ExamService getPassExamPort() {
        return super.getPort(new QName("http://asu.dgtu.donetsk.ua/ex/passexam", "PassExamPort"), ExamService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExamService
     */
    @WebEndpoint(name = "PassExamPort")
    public ExamService getPassExamPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://asu.dgtu.donetsk.ua/ex/passexam", "PassExamPort"), ExamService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PASSEXAM_EXCEPTION!= null) {
            throw PASSEXAM_EXCEPTION;
        }
        return PASSEXAM_WSDL_LOCATION;
    }

}
